# ---Base Image ---
From python:3.10-slim

# ---System Dependencies ---
Run apt-get update && apt-get install -y curl\
    && rm -rf /var/lib/apt/lists/*

# --- UV Install ---
Run curl -LsSf https://astral.sh/uv/install.sh | sh

# ---Add UV to Path---
ENV PATH="/root/.local/bin:${PATH}"

# ---App setup---
WORKDIR /app

# ---Copy dependency files---
COPY pyproject.toml uv.lock ./

# ---Install dependencies using UV---
RUN /root/.local/bin/uv sync --frozen --no-dev


# Copy application files
COPY . .

# ---Expose Ports---
EXPOSE 8000 

# ---Run FastAPI with Uvicorn---
CMD ["/root/.local/bin/uv", "run", "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]