apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-app
  namespace: diabetes
  labels:
    app: diabetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes
  template:
    metadata:
      labels:
        app: diabetes
    
    spec:
      containers:
        - name: diabetes-container
          image: 616426097428.dkr.ecr.ap-south-1.amazonaws.com/diabetes-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 8501