name: CI Pipeline

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest
# temp comment to force git detect change
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          uv run pytest -q

      # 👇 AWS + Docker steps ONLY on main push
      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        if: github.event_name == 'push'
        run: |
          docker build -t diabetes-app .

      - name: Tag Docker Image
        if: github.event_name == 'push'
        run: |
          docker tag diabetes-app:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.DIABETES_APP }}:latest

      - name: Push Docker Image TO ECR
        if: github.event_name == 'push'
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.DIABETES_APP }}:latest


